-- SETUP CONSOLIDATED INTELLIGENCE SCHEMAS AND TABLES
-- Run this in your Supabase SQL Editor to ensure all target tables exist.

-- 1. GOVERNMENT & POLITICS
CREATE SCHEMA IF NOT EXISTS gov_intelligence;

CREATE TABLE IF NOT EXISTS gov_intelligence.election_news (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    source_url text NOT NULL UNIQUE,
    title text,
    published timestamp with time zone,
    sentiment text,
    ai_summary text,
    entities text[],
    metadata jsonb,
    image_url text,
    topic text
);

-- 2. CRIME & SAFETY
CREATE SCHEMA IF NOT EXISTS crime_intelligence;

CREATE TABLE IF NOT EXISTS crime_intelligence.incidents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    source_url text NOT NULL UNIQUE,
    title text,
    description text,
    occurred_at timestamp with time zone,
    type text,
    severity_level text,
    status text,
    location text,
    published_at timestamp with time zone,
    image_url text
);

CREATE TABLE IF NOT EXISTS crime_intelligence.syndicates (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    name text NOT NULL,
    type text,
    primary_territory text,
    metadata jsonb
);

-- 3. SPORTS
CREATE SCHEMA IF NOT EXISTS sports_intelligence;

CREATE TABLE IF NOT EXISTS sports_intelligence.news (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    url text NOT NULL UNIQUE,
    title text,
    published timestamp with time zone,
    category text,
    ai_summary text,
    sentiment text,
    source text,
    image_url text,
    snippet_sources jsonb
);

-- 4. PEOPLE INTELLIGENCE (Rich Entities)
CREATE SCHEMA IF NOT EXISTS people_intelligence;

CREATE TABLE IF NOT EXISTS people_intelligence.master_identities (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    full_name text NOT NULL,
    type text,
    contact_verified boolean DEFAULT false,
    data_sources_count integer DEFAULT 0,
    last_seen_at timestamp with time zone
);

-- 5. BUSINESS INTELLIGENCE (Rich Entities)
CREATE SCHEMA IF NOT EXISTS business_intelligence;

CREATE TABLE IF NOT EXISTS business_intelligence.organizations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    registered_name text NOT NULL,
    type text,
    metadata jsonb
);

-- 6. SPECIALIZED NICHES (Generic Schema in ai_intelligence)
-- Ensure brics, energy, etc. exist if strictly routed there
CREATE TABLE IF NOT EXISTS ai_intelligence.brics (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    url text NOT NULL UNIQUE,
    title text,
    published timestamp with time zone,
    category text,
    ai_summary text,
    sentiment text,
    entities text[],
    location_text text,
    topic text,
    metadata jsonb,
    image_url text
);

CREATE TABLE IF NOT EXISTS ai_intelligence.energy (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    url text NOT NULL UNIQUE,
    title text,
    published timestamp with time zone,
    category text,
    ai_summary text,
    sentiment text,
    snippet_sources jsonb,
    image_url text
);

CREATE TABLE IF NOT EXISTS ai_intelligence.nuclear_energy (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    url text NOT NULL UNIQUE,
    title text,
    published timestamp with time zone,
    category text,
    ai_summary text,
    sentiment text,
    snippet_sources jsonb,
    image_url text
);

-- Enable RLS (Optional, recommended)
ALTER TABLE gov_intelligence.election_news ENABLE ROW LEVEL SECURITY;
ALTER TABLE crime_intelligence.incidents ENABLE ROW LEVEL SECURITY;
ALTER TABLE crime_intelligence.syndicates ENABLE ROW LEVEL SECURITY;
ALTER TABLE sports_intelligence.news ENABLE ROW LEVEL SECURITY;
ALTER TABLE people_intelligence.master_identities ENABLE ROW LEVEL SECURITY;
ALTER TABLE business_intelligence.organizations ENABLE ROW LEVEL SECURITY;
